# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarqueeTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'QMUIKit'
  pod 'Masonry', '~> 1.1.0'
  # Pods for MarqueeTest

  target 'MarqueeTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarqueeTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
