# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
 inhibit_all_warnings!

target 'CDCountdownTimerLabel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CDCountdownTimerLabel
#倒计时
pod 'MZTimerLabel', '~> 0.5.4'
pod 'Masonry', '~> 1.1.0'

end
