# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
inhibit_all_warnings!

target 'DragAndPlayDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod 'pop'
  
  #阿里高级播放器
  pod 'AliyunPlayer_iOS/AliyunVodPlayerSDK', '~> 3.4.8'
  
  pod 'Masonry', '~> 1.1.0'
  # Pods for DragAndPlayDemo

  target 'DragAndPlayDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DragAndPlayDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
